# #10. [2588] 곱셈
---

## 문제
(세 자리 수) × (세 자리 수)는 다음과 같은 과정을 통하여 이루어진다.

![image.png]()

(1)과 (2)위치에 들어갈 세 자리 자연수가 주어질 때 (3), (4), (5), (6)위치에 들어갈 값을 구하는 프로그램을 작성하시오.

---

## 입력
첫째 줄에 (1)의 위치에 들어갈 세 자리 자연수가, 둘째 줄에 (2)의 위치에 들어갈 세자리 자연수가 주어진다.

---

## 출력
첫째 줄부터 넷째 줄까지 차례대로 (3), (4), (5), (6)에 들어갈 값을 출력한다.

---
링크 : https://www.acmicpc.net/problem/2588

In [ ]:
n1 = int(input())
n2 = int(input())

n3 = n1 * (n2 % 10)
n4 = n1 * (n2 % 100 // 10)
n5 = n1 * (n2 // 100)
n6 = n1 * n2

print(n3)
print(n4)
print(n5)
print(n6)

472
385
2360
3776
1416
181720